version: "3"
services:
  linbpq:
    image: ve3lsr/allmon2
    build: .
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./allmon.ini.php:/var/www/html/allmon.ini.php
      - ./.htpasswd:/var/www/html/.htpasswd
